# Generated by Django 6.0 on 2026-02-16 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Аватар')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='background_image', verbose_name='Фоновое изображение')),
                ('first_name', models.CharField(max_length=10, verbose_name='Имя пользователя')),
                ('profission', models.CharField(blank=True, max_length=30, null=True, verbose_name='Професия')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Биография')),
                ('Instagram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на GitHub')),
                ('discord_username', models.CharField(blank=True, max_length=35, null=True, verbose_name='Ссылка на Discord')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
