# Generated by Django 6.0 on 2026-02-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_biousers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biousers',
            name='discord_username',
        ),
        migrations.AddField(
            model_name='biousers',
            name='discord_url',
            field=models.URLField(blank=True, max_length=35, null=True, verbose_name='Ссылка на Discord канал'),
        ),
        migrations.AddField(
            model_name='biousers',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на spotify плейлист'),
        ),
        migrations.AddField(
            model_name='biousers',
            name='steam_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на steam'),
        ),
        migrations.AddField(
            model_name='biousers',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на telegram'),
        ),
        migrations.AddField(
            model_name='biousers',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на ТТ'),
        ),
    ]
