# Generated by Django 6.0 on 2026-02-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_biousers_discord_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biousers',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя пользователя'),
        ),
    ]
