# Generated by Django 6.0 on 2026-01-28 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='SetupPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название поста')),
                ('main_photo', models.ImageField(upload_to='main_photo')),
                ('more_photo1', models.ImageField(blank=True, null=True, upload_to='morePhoto1')),
                ('more_photo2', models.ImageField(blank=True, null=True, upload_to='morePhoto2')),
                ('more_photo3', models.ImageField(blank=True, null=True, upload_to='morePhoto3')),
                ('cpu', models.CharField(max_length=20, verbose_name='CPU')),
                ('gpu', models.CharField(max_length=20, verbose_name='GPU')),
                ('ram', models.CharField(max_length=20, verbose_name='RAM')),
                ('ssd', models.CharField(max_length=30, verbose_name='Накопитель')),
                ('monitor', models.CharField(max_length=30, verbose_name='Монитор')),
                ('ps', models.CharField(blank=True, max_length=30, null=True, verbose_name='Блок питания')),
                ('comment', models.CharField(max_length=100, verbose_name='Дополнение')),
                ('story_setup', models.TextField(blank=True, null=True, verbose_name='История Сборки')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tegs', models.ManyToManyField(blank=True, to='main.tag', verbose_name='Теги')),
            ],
        ),
    ]
