# Generated by Django 6.0 on 2026-01-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setupposts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupposts',
            name='tegs',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.tag', verbose_name='Теги'),
        ),
    ]
