# Generated by Django 6.0 on 2026-02-04 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_setupposts_tegs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setupposts',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setupposts',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнение'),
        ),
        migrations.AlterField(
            model_name='setupposts',
            name='cpu',
            field=models.CharField(max_length=20, verbose_name='Процесор'),
        ),
        migrations.AlterField(
            model_name='setupposts',
            name='gpu',
            field=models.CharField(max_length=20, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='setupposts',
            name='ps',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='БП'),
        ),
        migrations.AlterField(
            model_name='setupposts',
            name='ram',
            field=models.CharField(max_length=20, verbose_name='Оперативка'),
        ),
    ]
