# Generated by Django 6.0 on 2026-02-25 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='Shop/main_photo')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('state', models.CharField(choices=[('used', 'Б/У'), ('new', 'Новое'), ('average', 'Среднее'), ('spareparts', 'На запчасти')], default='used', max_length=20)),
                ('manufacture', models.CharField(max_length=100)),
                ('guarantee', models.CharField(max_length=100)),
                ('complete', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_to', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Shop/additional_photo')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photo', to='Shop.announcement')),
            ],
        ),
    ]
