# Generated by Django 6.0 on 2026-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_announcement_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='state',
            field=models.CharField(choices=[('gpu', 'Видеокарта'), ('cpu', 'Процессор'), ('psu', 'Блок питания'), ('ram', 'Оперативка'), ('motherboard', 'Материнская плата'), ('cooler', 'Охлаждение'), ('case', 'Корпус'), ('ssd', 'SSD'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('others', 'Другое')], default='others', max_length=20),
        ),
    ]
