# Generated by Django 6.0 on 2026-03-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_announcement_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='state_components',
            field=models.CharField(choices=[('gpu', 'Видеокарта'), ('cpu', 'Процессор'), ('psu', 'Блок питания'), ('ram', 'Оперативка'), ('motherboard', 'Материнская плата'), ('cooler', 'Охлаждение'), ('case', 'Корпус'), ('ssd', 'SSD'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('others', 'Другое')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='state',
            field=models.CharField(choices=[('used', 'Б/У'), ('new', 'Новое'), ('average', 'Среднее'), ('spareparts', 'На запчасти')], default='used', max_length=20),
        ),
    ]
